name: PaperAntiCheat
version: 1.0.0
main: com.anticheat.Main
api-version: 1.16
depend: [ProtocolLib]
commands:
  anticheat:
    description: 反作弊系统管理命令
    usage: /anticheat [reload|status]
    permission: anticheat.admin
